[[plugins]]
  package = "netlify-plugin-password-protection"

  [plugins.inputs]
    password = "Simou2015"
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/tmp/cc-agent/66713461/project/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]